Test case "parallel_flash_identify"
===================================
Christoph Thelen <cthelen@hilscher.com>
:Author Initials: CT


[[About, About]]
== About

This document describes the "Parallel Flash identify" test for the Muhkuh test framework. It identifies a connected parallel NOR flash with the "flasher" tool. The chapter <<Test_description>> discusses this method in detail.

This test does not check extra lines of a 4 bit connection. Please see the "sqi_xip_test" for this purpose.


[[Test_description,Test description]]
== Test description

The test uses the flasher tool to identify the parallel NOR flash. The flasher is an open source project. It is hosted on GitHub: https://github.com/muhkuh-sys/org.muhkuh.tools-flasher .
The complete source code can be found in the public Git repository: https://github.com/muhkuh-sys/org.muhkuh.tools-flasher.git

The flasher detects parallel NOR flashes with the "Common Flash Memory Interface" (short CFI). CFI is a JEDEC standard: http://www.jedec.org/standards-documents/docs/jesd-6801/

The test can optionally write a file to the flash after a successful identify. The offset in the flash array can be selected.


[[Parameters, Parameters]]
== Parameters

+unit+::
  Specify the index of the unit where the parallel flash is connected. Please see the chapter <<Unit_and_Chip_select>> for details.
+chipselect+::
  Specify the index of the chip select where the parallel flash is connected. Please see the chapter <<Unit_and_Chip_select>> for details.
+data_file+::
  The path to the file which should be flashed after a successful identify.
+offset+::
  The offset in bytes for the flash operation. The default value of 0 writes the data file to the start of the flash.

[[Unit_and_Chip_select, Unit and chip select]]
=== Unit and chip select

TODO...
